name: Deploy react + Vite to Github Pages

on:
  push:
    branches: -main

jobs:
  buid-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      #Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
        node-version: 18

      # Install dependencies
      - name: Install dependencies
        uses: npm install

        # Build the project
      - name: Build project
        uses: npm run build

      # Deploy to github pages
      - name: Deploy
        uses: peaceiris/actios-gh-pages@v3
